// Mocks generated by Mockito 5.0.15 from annotations
// in card_seu_resumo_ui/test/presentation/presenters/store_resumo_presenter_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:card_seu_resumo_ui/app/domain/entities/entities.dart' as _i4;
import 'package:card_seu_resumo_ui/app/domain/usecases/load_resumo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [LoadResumo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadResumo extends _i1.Mock implements _i2.LoadResumo {
  MockLoadResumo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ResumoEntity>> getResumos() =>
      (super.noSuchMethod(Invocation.method(#getResumos, []),
              returnValue:
                  Future<List<_i4.ResumoEntity>>.value(<_i4.ResumoEntity>[]))
          as _i3.Future<List<_i4.ResumoEntity>>);
  @override
  String toString() => super.toString();
}
